spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.11.159:3306/cherrybnb
    username: cherry
    password: Test1test!

  sql:
    init:
      mode: always
