spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.34.113.208:3306/cherrybnb
    username: cherry
    password: Test1test!

  sql:
    init:
      mode: always
