spring:
  profiles:
    active: local

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
#        use_sql_comments: true
        jdbc:
          batch_size: 1000

    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect

    defer-datasource-initialization: true

logging.level:
  org.hibernate.SQL: debug

kakao.rest.api.key: ${KAKAO_REST_KEY}

github:
  client:
    id: ${GITHUB_CLIENT_ID}
    secrets: ${GITHUB_SECRETS}

server:
  port: 8080
